name: bookly_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  dartz: ^0.10.1
  cached_network_image: ^3.4.1
  get_it: ^8.0.2
  get: ^4.7.2
  http: ^1.3.0
  url_launcher: ^6.3.1  # ✅ أضف هذا للـ URL launcher

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter_18pt-Regular.ttf
    - family: GT Sectra Fine
      fonts:
        - asset: fonts/GT-Sectra-Fine-Regular.ttf